version: '3.9'
services:
  todo-app:
    build: .
    ports: 
      - 8000:8000
    environment: 
      POSTGRES_PASSWORD: qwerty
    depends_on:
      - postgres
      
  postgres:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: qwerty